import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [countryCode, setCountryCode] = useState("NL");
  const { data, error } = trpc.useQuery(["example.countries", { countryCode }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>
          Create <span>T3</span> App
        </h1>

        <div>
          <h3>This stack uses:</h3>
          <ul>
            <li>
              <a href="https://nextjs.org" target="_blank" rel="noreferrer">
                Next.js
              </a>
            </li>
            <li>
              <a href="https://trpc.io" target="_blank" rel="noreferrer">
                tRPC
              </a>
            </li>
            <li>
              <a
                href="https://typescriptlang.org"
                target="_blank"
                rel="noreferrer"
              >
                TypeScript
              </a>
            </li>
          </ul>

          <input
            onChange={(e) => setCountryCode(e.target.value)}
            value={countryCode}
          />

          <div>
            {data ? (
              <p>{JSON.stringify(data)}</p>
            ) : error?.message ? (
              error.message
            ) : (
              <p>Loading..</p>
            )}
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
